[2023-05-19 15:12:33,192] {processor.py:153} INFO - Started process (PID=2821) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:12:33,192] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 15:12:33,193] {logging_mixin.py:115} INFO - [2023-05-19 15:12:33,193] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:12:33,227] {logging_mixin.py:115} INFO - [2023-05-19 15:12:33,227] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 15:12:33,227] {logging_mixin.py:115} INFO - [2023-05-19 15:12:33,227] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 15:12:33,228] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:12:33,271] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.080 seconds
[2023-05-19 15:14:06,586] {processor.py:153} INFO - Started process (PID=2886) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:14:06,588] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 15:14:06,588] {logging_mixin.py:115} INFO - [2023-05-19 15:14:06,588] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:14:06,618] {logging_mixin.py:115} INFO - [2023-05-19 15:14:06,617] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 15:14:06,618] {logging_mixin.py:115} INFO - [2023-05-19 15:14:06,618] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 15:14:06,618] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:14:06,664] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.078 seconds
[2023-05-19 15:16:07,405] {processor.py:153} INFO - Started process (PID=2956) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:16:07,406] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 15:16:07,407] {logging_mixin.py:115} INFO - [2023-05-19 15:16:07,407] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:16:07,435] {logging_mixin.py:115} INFO - [2023-05-19 15:16:07,435] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 15:16:07,436] {logging_mixin.py:115} INFO - [2023-05-19 15:16:07,436] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 15:16:07,436] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:16:07,485] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.080 seconds
[2023-05-19 15:18:51,674] {processor.py:153} INFO - Started process (PID=3082) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:18:51,675] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 15:18:51,676] {logging_mixin.py:115} INFO - [2023-05-19 15:18:51,676] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:18:51,714] {logging_mixin.py:115} INFO - [2023-05-19 15:18:51,714] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 15:18:51,715] {logging_mixin.py:115} INFO - [2023-05-19 15:18:51,715] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 15:18:51,715] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:18:51,788] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.115 seconds
[2023-05-19 15:20:45,659] {processor.py:153} INFO - Started process (PID=3140) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:20:45,660] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 15:20:45,665] {logging_mixin.py:115} INFO - [2023-05-19 15:20:45,665] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:20:45,706] {logging_mixin.py:115} INFO - [2023-05-19 15:20:45,706] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 15:20:45,706] {logging_mixin.py:115} INFO - [2023-05-19 15:20:45,706] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 15:20:45,706] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:20:45,771] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.113 seconds
[2023-05-19 15:22:24,482] {processor.py:153} INFO - Started process (PID=3192) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:22:24,483] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 15:22:24,483] {logging_mixin.py:115} INFO - [2023-05-19 15:22:24,483] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:22:24,513] {logging_mixin.py:115} INFO - [2023-05-19 15:22:24,511] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 15:22:24,514] {logging_mixin.py:115} INFO - [2023-05-19 15:22:24,513] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 15:22:24,514] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:22:24,567] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.087 seconds
[2023-05-19 15:24:02,749] {processor.py:153} INFO - Started process (PID=3243) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:24:02,750] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 15:24:02,751] {logging_mixin.py:115} INFO - [2023-05-19 15:24:02,751] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:24:02,782] {logging_mixin.py:115} INFO - [2023-05-19 15:24:02,782] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 15:24:02,782] {logging_mixin.py:115} INFO - [2023-05-19 15:24:02,782] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 15:24:02,782] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:24:02,828] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.080 seconds
[2023-05-19 15:26:44,899] {processor.py:153} INFO - Started process (PID=3352) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:26:44,901] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 15:26:44,902] {logging_mixin.py:115} INFO - [2023-05-19 15:26:44,901] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:26:44,941] {logging_mixin.py:115} INFO - [2023-05-19 15:26:44,940] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 15:26:44,941] {logging_mixin.py:115} INFO - [2023-05-19 15:26:44,941] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 15:26:44,942] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:26:44,996] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2023-05-19 15:28:49,723] {processor.py:153} INFO - Started process (PID=3420) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:28:49,723] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 15:28:49,724] {logging_mixin.py:115} INFO - [2023-05-19 15:28:49,723] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:28:49,751] {logging_mixin.py:115} INFO - [2023-05-19 15:28:49,750] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 15:28:49,751] {logging_mixin.py:115} INFO - [2023-05-19 15:28:49,751] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 15:28:49,751] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 15:28:49,796] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2023-05-19 16:29:37,464] {processor.py:153} INFO - Started process (PID=6073) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 16:29:37,465] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 16:29:37,466] {logging_mixin.py:115} INFO - [2023-05-19 16:29:37,466] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 16:29:37,573] {logging_mixin.py:115} INFO - [2023-05-19 16:29:37,573] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 16:29:37,573] {logging_mixin.py:115} INFO - [2023-05-19 16:29:37,573] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 16:29:37,573] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 16:29:37,664] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.205 seconds
[2023-05-19 16:34:10,851] {processor.py:153} INFO - Started process (PID=6230) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 16:34:10,852] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 16:34:10,854] {logging_mixin.py:115} INFO - [2023-05-19 16:34:10,854] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 16:34:10,929] {logging_mixin.py:115} INFO - [2023-05-19 16:34:10,929] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 16:34:10,930] {logging_mixin.py:115} INFO - [2023-05-19 16:34:10,930] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 16:34:10,930] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 16:34:11,108] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.262 seconds
[2023-05-19 16:36:43,886] {processor.py:153} INFO - Started process (PID=6309) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 16:36:43,888] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 16:36:43,888] {logging_mixin.py:115} INFO - [2023-05-19 16:36:43,888] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 16:36:43,929] {logging_mixin.py:115} INFO - [2023-05-19 16:36:43,929] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 16:36:43,930] {logging_mixin.py:115} INFO - [2023-05-19 16:36:43,929] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 16:36:43,930] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 16:36:43,999] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.114 seconds
[2023-05-19 16:51:51,621] {processor.py:153} INFO - Started process (PID=6733) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 16:51:51,622] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 16:51:51,623] {logging_mixin.py:115} INFO - [2023-05-19 16:51:51,623] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 16:51:51,672] {logging_mixin.py:115} INFO - [2023-05-19 16:51:51,672] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 16:51:51,672] {logging_mixin.py:115} INFO - [2023-05-19 16:51:51,672] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 16:51:51,673] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 16:51:51,743] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.124 seconds
[2023-05-19 16:55:34,055] {processor.py:153} INFO - Started process (PID=6963) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 16:55:34,057] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 16:55:34,058] {logging_mixin.py:115} INFO - [2023-05-19 16:55:34,057] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 16:55:34,107] {logging_mixin.py:115} INFO - [2023-05-19 16:55:34,107] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 16:55:34,108] {logging_mixin.py:115} INFO - [2023-05-19 16:55:34,107] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 16:55:34,108] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 16:55:34,180] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.126 seconds
[2023-05-19 16:58:41,332] {processor.py:153} INFO - Started process (PID=7074) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 16:58:41,333] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 16:58:41,334] {logging_mixin.py:115} INFO - [2023-05-19 16:58:41,333] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 16:58:41,386] {logging_mixin.py:115} INFO - [2023-05-19 16:58:41,385] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 16:58:41,386] {logging_mixin.py:115} INFO - [2023-05-19 16:58:41,386] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 16:58:41,386] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 16:58:41,466] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.136 seconds
[2023-05-19 17:01:42,780] {processor.py:153} INFO - Started process (PID=7160) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:01:42,781] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 17:01:42,782] {logging_mixin.py:115} INFO - [2023-05-19 17:01:42,782] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:01:42,823] {logging_mixin.py:115} INFO - [2023-05-19 17:01:42,823] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 17:01:42,824] {logging_mixin.py:115} INFO - [2023-05-19 17:01:42,823] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 17:01:42,824] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:01:42,889] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.110 seconds
[2023-05-19 17:30:53,506] {processor.py:153} INFO - Started process (PID=7756) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:30:53,511] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 17:30:53,511] {logging_mixin.py:115} INFO - [2023-05-19 17:30:53,511] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:30:53,557] {logging_mixin.py:115} INFO - [2023-05-19 17:30:53,557] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 17:30:53,557] {logging_mixin.py:115} INFO - [2023-05-19 17:30:53,557] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 17:30:53,558] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:30:53,627] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.123 seconds
[2023-05-19 17:33:48,184] {processor.py:153} INFO - Started process (PID=7826) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:33:48,186] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 17:33:48,186] {logging_mixin.py:115} INFO - [2023-05-19 17:33:48,186] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:33:48,265] {logging_mixin.py:115} INFO - [2023-05-19 17:33:48,264] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 17:33:48,265] {logging_mixin.py:115} INFO - [2023-05-19 17:33:48,265] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 17:33:48,265] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:33:48,529] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.346 seconds
[2023-05-19 17:38:14,500] {processor.py:153} INFO - Started process (PID=7932) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:38:14,501] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 17:38:14,505] {logging_mixin.py:115} INFO - [2023-05-19 17:38:14,505] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:38:14,620] {logging_mixin.py:115} INFO - [2023-05-19 17:38:14,619] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 17:38:14,620] {logging_mixin.py:115} INFO - [2023-05-19 17:38:14,620] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 17:38:14,621] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:38:14,996] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.499 seconds
[2023-05-19 17:45:31,426] {processor.py:153} INFO - Started process (PID=8108) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:45:31,427] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 17:45:31,429] {logging_mixin.py:115} INFO - [2023-05-19 17:45:31,429] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:45:31,512] {logging_mixin.py:115} INFO - [2023-05-19 17:45:31,512] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 17:45:31,512] {logging_mixin.py:115} INFO - [2023-05-19 17:45:31,512] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 17:45:31,513] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:45:31,632] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.212 seconds
[2023-05-19 17:47:52,662] {processor.py:153} INFO - Started process (PID=8171) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:47:52,663] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 17:47:52,663] {logging_mixin.py:115} INFO - [2023-05-19 17:47:52,663] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:47:52,731] {logging_mixin.py:115} INFO - [2023-05-19 17:47:52,730] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 17:47:52,731] {logging_mixin.py:115} INFO - [2023-05-19 17:47:52,731] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 17:47:52,732] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:47:52,823] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.164 seconds
[2023-05-19 17:51:01,281] {processor.py:153} INFO - Started process (PID=8268) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:51:01,285] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 17:51:01,286] {logging_mixin.py:115} INFO - [2023-05-19 17:51:01,285] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:51:01,337] {logging_mixin.py:115} INFO - [2023-05-19 17:51:01,337] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 17:51:01,337] {logging_mixin.py:115} INFO - [2023-05-19 17:51:01,337] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 17:51:01,337] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:51:01,435] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.155 seconds
[2023-05-19 17:54:35,272] {processor.py:153} INFO - Started process (PID=8444) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:54:35,273] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 17:54:35,274] {logging_mixin.py:115} INFO - [2023-05-19 17:54:35,274] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:54:35,320] {logging_mixin.py:115} INFO - [2023-05-19 17:54:35,320] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 17:54:35,320] {logging_mixin.py:115} INFO - [2023-05-19 17:54:35,320] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 17:54:35,320] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:54:35,402] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.132 seconds
[2023-05-19 17:57:34,003] {processor.py:153} INFO - Started process (PID=8598) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:57:34,004] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 17:57:34,004] {logging_mixin.py:115} INFO - [2023-05-19 17:57:34,004] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:57:34,063] {logging_mixin.py:115} INFO - [2023-05-19 17:57:34,062] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 17:57:34,063] {logging_mixin.py:115} INFO - [2023-05-19 17:57:34,063] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 17:57:34,063] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 17:57:34,137] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.136 seconds
[2023-05-19 18:15:21,793] {processor.py:153} INFO - Started process (PID=9222) to work on /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 18:15:21,796] {processor.py:641} INFO - Processing file /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-05-19 18:15:21,797] {logging_mixin.py:115} INFO - [2023-05-19 18:15:21,796] {dagbag.py:507} INFO - Filling up the DagBag from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 18:15:21,893] {logging_mixin.py:115} INFO - [2023-05-19 18:15:21,891] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-05-19 18:15:21,894] {logging_mixin.py:115} INFO - [2023-05-19 18:15:21,893] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-05-19 18:15:21,894] {processor.py:653} WARNING - No viable dags retrieved from /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-05-19 18:15:22,053] {processor.py:161} INFO - Processing /Users/marianaoliveira/Downloads/alura1/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.265 seconds
